<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.5" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.5" />
    <PackageReference Include="Avalonia.LinuxFramebuffer" Version="11.3.5" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.5" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.5" />
    <PackageReference Include="Avalonia.Diagnostics" Version="11.3.5">
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Avalonia3D.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Assets\TestScenes\*.gltf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
